# Common Armbian build settings for all LinknLink iSG Box SE images.
BOARD=linknlink-isg-box-se
BRANCH=vendor
RELEASE=bookworm
BUILD_MINIMAL=no
BUILD_DESKTOP=no
KERNEL_CONFIGURE=no
KERNEL_BTF=no
NETWORKING_STACK=network-manager
NAMESERVER=1.1.1.1
ENABLE_EXTENSIONS=isg-build-network,isg-fast-kernel-config,isg-image-flavor,isg-seekwave-driver
